In [1]:
import cv2
import matplotlib.pyplot as plt
import os
import numpy as np
import glob


In [2]:
CALIBRATION_IMAGE_DIR = 'C:\\Users\\JakeC\\OneDrive\\Documents\\GitHub\\ComputerVision\\iPhone Camera Calibrate\\Subfolder1'


In [9]:
criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 30, 0.001)
# prepare object points, like (0,0,0), (1,0,0), (2,0,0) ....,(6,5,0)
objp = np.zeros((6*9,3), np.float32)
objp[:,:2] = np.mgrid[0:9,0:6].T.reshape(-1,2)
# Arrays to store object points and image points from all the images.
objpoints = [] # 3d point in real world space
imgpoints = [] # 2d points in image plane.
images = glob.glob(os.path.join(CALIBRATION_IMAGE_DIR, '*.JPG'))
sharpenKernel = np.array([[-1,-1,-1], [-1,9,-1], [-1,-1,-1]])

In [10]:
i = 0

for fname in images:
    # print(1)
    img = cv2.imread(fname)
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    downsize = cv2.resize(gray, (0, 0), fx = 0.2, fy = 0.2)
    # sharpened = cv2.filter2D(gray, -1, sharpenKernel)
    # Find the chess board corners
    # print(2)
    # cv2.imshow('img', img)
    # cv2.waitKey(0)
    ret, corners = cv2.findChessboardCorners(downsize, (9,6), None)
    # print(3)
    # If found, add object points, image points (after refining them)
    
    if ret == True:

        print('found' + str(i))
        objpoints.append(objp)
        corners2 = cv2.cornerSubPix(downsize ,corners, (11,11), (-1,-1), criteria) * 5
        # print(corners2 * 5)
        imgpoints.append(corners2)
        # Draw and display the corners
        cv2.drawChessboardCorners(img, (9,6), corners2, ret)
        # cv2.imshow('img', img)
        # cv2.imwrite('C:\\Users\\JakeC\\OneDrive\\Documents\\GitHub\\ComputerVision\\iPhone Camera Calibrate\\test\\' + str(i)+ '.jpg',img)
        # cv2.waitKey(0)
        i += 1

found0
found1
found2
found3
found4
found5
found6
found7
found8
found9
found10
found11
found12


In [6]:
print(imgpoints)
print(len(objpoints))

[array([[[2642.3489 ,  353.60275]],

       [[2643.5933 ,  534.33325]],

       [[2647.738  ,  722.40204]],

       [[2647.5442 ,  917.8897 ]],

       [[2647.6309 , 1117.5463 ]],

       [[2648.457  , 1319.6083 ]],

       [[2652.0056 , 1532.7029 ]],

       [[2652.79   , 1753.6199 ]],

       [[2652.9507 , 1976.0562 ]],

       [[2427.7292 ,  368.08704]],

       [[2425.3276 ,  548.095  ]],

       [[2422.4197 ,  734.225  ]],

       [[2422.401  ,  927.93835]],

       [[2417.3677 , 1123.6404 ]],

       [[2417.2183 , 1327.314  ]],

       [[2412.7212 , 1537.8163 ]],

       [[2412.3618 , 1747.5195 ]],

       [[2407.6345 , 1967.129  ]],

       [[2217.6365 ,  386.42242]],

       [[2212.831  ,  563.17053]],

       [[2207.9202 ,  747.236  ]],

       [[2203.386  ,  937.53845]],

       [[2197.2114 , 1132.5979 ]],

       [[2188.669  , 1331.3586 ]],

       [[2181.5337 , 1538.4062 ]],

       [[2177.8396 , 1750.1162 ]],

       [[2172.8838 , 1961.8861 ]],

       [[2011.9016 ,  402.9

In [11]:
ret, mtx, dist, rvecs, tvecs = cv2.calibrateCamera(objpoints, imgpoints, gray.shape[::-1], None, None)

In [12]:
print(mtx)

[[3.40709589e+03 0.00000000e+00 1.51241852e+03]
 [0.00000000e+00 3.39791102e+03 1.89852034e+03]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]
